// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piqamkedvygqaqmxxvqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpcWFta2VkdnlncWFxbXh4dnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzY4NjgsImV4cCI6MjA2NzkxMjg2OH0.q0w1LzVuhlfvAlYFFoHjH1wPXIoogLrXnLD68vqvrkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});